### ISSUE TITLE
Train Tacotron with JSUT dataset

### ISSUE THREAD

**Issue by rild** [rild/TIL#34]
https://github.com/r9y9/deepvoice3_pytorch/blob/master/train.py

を動かす

# 目的
JSUTの前処理を確認する。
ローマ字をテキストの入力にしているかどうかを確認する。
日本語の合成ができるかどうか確認する。

# 背景
- tacotron を日本語対応させるために、データの前処理がしたかった。
- pykakasi をつかって、ローマ字に変換してから入力データとして使おうとした。

---
- pykakasi の辞書に存在しない単語を変換しようとすること

の影響で、読み上げとテキストが一致しない場合があり、一旦、自分で keithito/tacotron 用に JSUT データを整形することを中断した。

**Comment by rild** [comment]
```
>>> from nnmnkwii.datasets import jsut
>>>
```

を確認。

```
pip install nnmnkwii 
```
では、 JSUT のモジュールが入っていない ([Change log](https://r9y9.github.io/nnmnkwii/latest/changelog.html) で確認) v0.0.8 が入ってしまうため、

```
$ pip install git+https://github.com/r9y9/nnmnkwii
```

でインストールを行った。

**Comment by rild** [comment]
`preprocess.py` を実行して、`./data/jsut` を作ることには成功

**Comment by rild** [comment]
`$ python setup.py build` を実行した時に cuda.h と  ATen/ATen.h でエラーが起きてしまったので、

```
export CPATH='/opt/cuda/include:/opt/aten/include
```

を実行した後に, 
build → develop の操作を行った。

---
(備考)

- cuda 8
を `pacman` で install 

- ATen 
を [zdevito/ATen](https://github.com/zdevito/ATen) にある通りに install
> この時コンパイルに gcc-5 を要求されたので、gcc を alias で無理やり gcc-5 に通した後に実行した。

**Comment by rild** [comment]
```log
$ python setup.py build 
running build
running build_py
generating /tmp/tmpbk8oefuw/_temporal_convolution_tbc.cpp
setting the current directory to '/tmp/tmpbk8oefuw'
running build_ext
building '_temporal_convolution_tbc' extension
creating home2
creating home2/iida
creating home2/iida/tmp
creating home2/iida/tmp/fairseq-py
creating home2/iida/tmp/fairseq-py/fairseq
creating home2/iida/tmp/fairseq-py/fairseq/clib
creating home2/iida/tmp/fairseq-py/fairseq/clib/temporal_convolution_tbc
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -fPIC -DWITH_CUDA -I/usr/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/usr/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/usr/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/include/python3.6m -c _temporal_convolution_tbc.cpp -o ./_temporal_convolution_tbc.o -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -fPIC -DWITH_CUDA -I/usr/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/usr/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/usr/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/include/python3.6m -c /home2/iida/tmp/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.cpp -o ./home2/iida/tmp/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.o -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
g++ -pthread -shared -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now ./_temporal_convolution_tbc.o ./home2/iida/tmp/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.o -L/usr/lib -lpython3.6m -o ./_temporal_convolution_tbc.so
copying fairseq/temporal_convolution_tbc/__init__.py -> build/lib.linux-x86_64-3.6/fairseq/temporal_convolution_tbc
running egg_info
writing fairseq.egg-info/PKG-INFO
writing dependency_links to fairseq.egg-info/dependency_links.txt
writing requirements to fairseq.egg-info/requires.txt
writing top-level names to fairseq.egg-info/top_level.txt
reading manifest file 'fairseq.egg-info/SOURCES.txt'
writing manifest file 'fairseq.egg-info/SOURCES.txt'
copying fairseq/temporal_convolution_tbc/_temporal_convolution_tbc.so -> build/lib.linux-x86_64-3.6/fairseq/temporal_convolution_tbc
running build_ext
```

**Comment by rild** [comment]
```
$ python setup.py develop                           
running develop
running egg_info
writing fairseq.egg-info/PKG-INFO
writing dependency_links to fairseq.egg-info/dependency_links.txt
writing requirements to fairseq.egg-info/requires.txt
writing top-level names to fairseq.egg-info/top_level.txt
reading manifest file 'fairseq.egg-info/SOURCES.txt'
writing manifest file 'fairseq.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-x86_64-3.6/fairseq/libbleu.cpython-36m-x86_64-linux-gnu.so -> fairseq
Creating /usr/lib/python3.6/site-packages/fairseq.egg-link (link to .)
Removing fairseq 0.2.0 from easy-install.pth file
Adding fairseq 0.2.0 to easy-install.pth file

Installed /home2/iida/tmp/fairseq-py
Processing dependencies for fairseq==0.2.0
Searching for tqdm==4.19.4
Best match: tqdm 4.19.4
Adding tqdm 4.19.4 to easy-install.pth file
Installing tqdm script to /usr/bin

Using /usr/lib/python3.6/site-packages
Searching for torch==0.2.0.post3
Best match: torch 0.2.0.post3
Adding torch 0.2.0.post3 to easy-install.pth file

Using /usr/lib/python3.6/site-packages
Searching for numpy==1.13.3
Best match: numpy 1.13.3
Adding numpy 1.13.3 to easy-install.pth file

Using /usr/lib/python3.6/site-packages
Searching for cffi==1.11.2
Best match: cffi 1.11.2
Adding cffi 1.11.2 to easy-install.pth file

Using /usr/lib/python3.6/site-packages
Searching for PyYAML==3.12
Best match: PyYAML 3.12
Adding PyYAML 3.12 to easy-install.pth file

Using /usr/lib/python3.6/site-packages
Searching for pycparser==2.18
Best match: pycparser 2.18
Adding pycparser 2.18 to easy-install.pth file

Using /usr/lib/python3.6/site-packages
Finished processing dependencies for fairseq==0.2.0
```

**Comment by rild** [comment]
### And....

```log
$ pip list | grep fairseq
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
fairseq (0.2.0, /home2/iida/tmp/fairseq-py)
```

**Comment by rild** [comment]
## train.py の実行時に fairseq 周りでエラーで止まってしまう

```console
$ python train.py --data-root=./data/jsut/
ERROR: missing temporal_convolution_tbc, run `python setup.py install`
Traceback (most recent call last):
  File "train.py", line 21, in <module>
    from deepvoice3_pytorch import frontend, build_deepvoice3
  File "/home2/iida/r9y9/deepvoice3_pytorch/deepvoice3_pytorch/__init__.py", line 5, in <module>
    from .deepvoice3 import *
  File "/home2/iida/r9y9/deepvoice3_pytorch/deepvoice3_pytorch/deepvoice3.py", line 10, in <module>
    from fairseq.models.fconv import Embedding, Linear, LinearizedConvolution
  File "/home2/iida/tmp/fairseq-py/fairseq/models/__init__.py", line 14, in <module>
    from . import fconv, lstm
  File "/home2/iida/tmp/fairseq-py/fairseq/models/fconv.py", line 16, in <module>
    from fairseq.modules import BeamableMM, GradMultiply, LinearizedConvolution
  File "/home2/iida/tmp/fairseq-py/fairseq/modules/__init__.py", line 10, in <module>
    from .conv_tbc import ConvTBC
  File "/home2/iida/tmp/fairseq-py/fairseq/modules/conv_tbc.py", line 18, in <module>
    raise e
  File "/home2/iida/tmp/fairseq-py/fairseq/modules/conv_tbc.py", line 14, in <module>
    from fairseq import temporal_convolution_tbc
  File "/home2/iida/tmp/fairseq-py/fairseq/temporal_convolution_tbc/__init__.py", line 3, in <module>
    from ._temporal_convolution_tbc import lib as _lib, ffi as _ffi
ImportError: /home2/iida/tmp/fairseq-py/fairseq/temporal_convolution_tbc/_temporal_convolution_tbc.so: undefined symbol: _ZN2at15UndefinedTensor10_singletonE
```

**Comment by rild** [comment]
[facebookresearch/fairseq-py](https://github.com/facebookresearch/fairseq-py/issues/31)

この issue と同じ現象か...

**Comment by r9y9** [comment]
まず念の為確認ですが、pytorchはソースからビルドして入れていますか？（たぶんしていますよね、、

僕が使っているpytorchのバージョンを貼っておきます

```
python -c "import torch; print(torch.__version__)"
0.2.0+47f999b
```

確か一週間くらい前の時点での最新です。最近はpytorchに破壊的な（atenのパスが変わったり）していたはずで、同じバージョンにして試してみるのもよいかもしれません

**Comment by rild** [comment]
@r9y9 さん、返信ありがとうございます!


pytorch は

http://pytorch.org/

こちらの

```
pip3 install http://download.pytorch.org/whl/cu80/torch-0.2.0.post3-cp35-cp35m-manylinux1_x86_64.whl 
pip3 install torchvision
```

を参考に、

```
pip3 install http://download.pytorch.org/whl/cu80/torch-0.2.0.post3-cp36-cp36m-manylinux1_x86_64.whl 
```

で install しました。

```
$ python -c "import torch; print(torch.__version__)"
0.2.0_3
```

**Comment by r9y9** [comment]
あ、いまfairseqを最新にしたら学習スクリプトが動かなくなっていました、、

https://github.com/r9y9/deepvoice3_pytorch/commit/1666ed26df8335a11b64c5e7fe498791982dc279 直しましたので、最新版を使ってください

あともう一点、前処理をすでに行ってもらったようなのですが、ちょうど今音声処理のバックエンドを書きなおした (https://github.com/r9y9/deepvoice3_pytorch/commit/728c73b2a55990ceb2f6d35ed1fba8a01a52af9b) ところなので、新しいバージョンで使うには再度前処理を行う必要があります。また、 https://github.com/Jonathan-LeRoux/lws をインストールする必要があるのに注意してください

ちょうどいま僕が色々実験を行っているリポジトリなので、いろんな変更がほぼ毎日あるかもしれません。破壊的な変更はやめてくれ、、ということであれば、forkして使ってもらうのがよいかもしれません！

**Comment by rild** [comment]
aten は 個別にソースビルドで install しています。

先に、 pytorch を入れていたのですが、
ATen.h がない、とのことで、 fairseq のビルドに失敗してしまったため...

**Comment by rild** [comment]
最新版試して見ます！

実験大歓迎です。
もっと良くなっていくところをまじかで見られたら嬉しいです！

**Comment by r9y9** [comment]
https://github.com/facebookresearch/fairseq-py#requirements-and-installation

> Currently fairseq-py requires installing PyTorch from source. Please follow the instructions here: https://github.com/pytorch/pytorch#from-source.

fairseqを使うには、面倒ですが、pytorchのリポジトリをクローンして、自分でビルドする必要があります。ソースからビルドすれば、きっとAten.hがない云々の問題は解決すると思います。

**Comment by rild** [comment]
承知しました。
先に pytorch をソースビルドしてから、もう一度 fairseq を試してみます。
ありがとうございます ><

**Comment by rild** [comment]
# 追記１
pytorch を github から clone して、ソースビルドしたところ、 fairseq の install が完了
pytorch の最新版が v0.4 になっていたため、 install されたのは、 v0.4 だが、一応うまく動いた

設定をしようとした PC で再度、 `train.py` を実行したところ、
hparam の読み込みが終わり、データで学習を開始した

そのマシンに刺さっている GPU (Quadro P1000)  のバッファ領域 (4G しかない) が原因と思われる RuntimeError を出してしまった。

```
14it [00:20,  1.44s/it]THCudaCheck FAIL file=/home2/iida/tmp/pytorch/aten/src/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "train.py", line 593, in <module>
    clip_thresh=hparams.clip_thresh)
  File "train.py", line 472, in train
    loss.backward()
  File "/usr/lib/python3.6/site-packages/torch/autograd/variable.py", line 165, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/usr/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
  File "/usr/lib/python3.6/site-packages/torch/autograd/function.py", line 91, in apply
    return self._forward_cls.backward(self, *args)
  File "/usr/lib/python3.6/site-packages/torch/nn/_functions/dropout.py", line 48, in backward
    return grad_output.mul(Variable(ctx.noise)), None, None, None
RuntimeError: cuda runtime error (2) : out of memory at /home2/iida/tmp/pytorch/aten/src/THC/generic/THCStorage.
```

**Comment by rild** [comment]
Tesla K40 が刺さっているマシンで環境設定を行って、 `train.py`  を実行したところ

torch + cuda 周りでエラーが起きてしまった

```console
  weight_decay: 0.0
0it [00:00, ?it/s]Traceback (most recent call last):
  File "train.py", line 598, in <module>
    clip_thresh=hparams.clip_thresh)
  File "train.py", line 384, in train
    in tqdm(enumerate(data_loader)):
  File "/usr/lib/python3.6/site-packages/tqdm/_tqdm.py", line 949, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 201, in __next__
    return self._process_next_batch(batch)
  File "/usr/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 221, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AssertionError: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 62, in _pin_memory_loop
    batch = pin_memory_batch(batch)
  File "/usr/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 123, in pin_memory_batch
    return [pin_memory_batch(sample) for sample in batch]
  File "/usr/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 123, in <listcomp>
    return [pin_memory_batch(sample) for sample in batch]
  File "/usr/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 117, in pin_memory_batch
    return batch.pin_memory()
  File "/usr/lib/python3.6/site-packages/torch/tensor.py", line 82, in pin_memory
    return type(self)().set_(storage.pin_memory()).view_as(self)
  File "/usr/lib/python3.6/site-packages/torch/storage.py", line 83, in pin_memory
    allocator = torch.cuda._host_allocator()
  File "/usr/lib/python3.6/site-packages/torch/cuda/__init__.py", line 220, in _host_allocator
    _lazy_init()
  File "/usr/lib/python3.6/site-packages/torch/cuda/__init__.py", line 84, in _lazy_init
    _check_driver()
  File "/usr/lib/python3.6/site-packages/torch/cuda/__init__.py", line 51, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

**Comment by r9y9** [comment]
現時点でのデフォルトハイパーパラメータでは、だいたいGPUメモリを3GBくらい使用するので、もしメモリが足りない場合は、 

- バッチサイズを小さくする
 https://github.com/r9y9/deepvoice3_pytorch/blob/a93535d7e2caa170608b068faac1287960efd295/hparams.py#L53 
- `cudnn.benchmark=False` にする https://github.com/r9y9/deepvoice3_pytorch/blob/a93535d7e2caa170608b068faac1287960efd295/train.py#L53

と、メモリ消費を抑えられるので、必要であれば試してみてください

**Comment by rild** [comment]
追記

GPU のメモリが足りないものの、pytorch のソースビルドが(なぜか)上手くいった方の  `/usr/lib/python3.6/site-packages/` 以下の torch, torch-0.4.0 をコピーして移植してその場しのぎにした

`train.py` を実行することはできた


pytorch のソースビルドが上手くいった・いかない理由は未だ分からず
一旦この issue はクローズ

**Comment by rild** [comment]
@r9y9 返信に気がつかずすみませんでした。
アドバイス、ありがとうございます！

Quadro P1000 を使っているので、4G あるはずなので、もう一度試してみます。
